"""create daily fruit tables

Revision ID: 0001
Revises: 
Create Date: 2026-07-31 18:05:12.765935
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """创建 public 业务表、约束、索引和历史记录的基础结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruits',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('taste', sa.String(length=120), nullable=False),
    sa.Column('sweet_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('sour_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('soft_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('crisp_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('convenience_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('average_price_level', sa.SmallInteger(), nullable=False),
    sa.Column('default_portion', sa.String(length=80), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_price_level BETWEEN 1 AND 3', name='ck_fruits_average_price_level_range'),
    sa.CheckConstraint('convenience_score BETWEEN 0 AND 1', name='ck_fruits_convenience_score_range'),
    sa.CheckConstraint('crisp_score BETWEEN 0 AND 1', name='ck_fruits_crisp_score_range'),
    sa.CheckConstraint('soft_score BETWEEN 0 AND 1', name='ck_fruits_soft_score_range'),
    sa.CheckConstraint('sour_score BETWEEN 0 AND 1', name='ck_fruits_sour_score_range'),
    sa.CheckConstraint('sweet_score BETWEEN 0 AND 1', name='ck_fruits_sweet_score_range'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fruits')),
    sa.UniqueConstraint('name', name='uq_fruits_name'),
    schema='public'
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('sweet_preference', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('sour_preference', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('soft_preference', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('crisp_preference', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('price_level', sa.SmallInteger(), nullable=False),
    sa.Column('convenience_preference', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('convenience_preference BETWEEN 0 AND 1', name='ck_users_convenience_preference_range'),
    sa.CheckConstraint('crisp_preference BETWEEN 0 AND 1', name='ck_users_crisp_preference_range'),
    sa.CheckConstraint('price_level BETWEEN 1 AND 3', name='ck_users_price_level_range'),
    sa.CheckConstraint('soft_preference BETWEEN 0 AND 1', name='ck_users_soft_preference_range'),
    sa.CheckConstraint('sour_preference BETWEEN 0 AND 1', name='ck_users_sour_preference_range'),
    sa.CheckConstraint('sweet_preference BETWEEN 0 AND 1', name='ck_users_sweet_preference_range'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='public'
    )
    op.create_table('fruit_nutritions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('fruit_id', sa.BigInteger(), nullable=False),
    sa.Column('energy', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vitamin_c', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fiber', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('potassium', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('folate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carotenoids', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('carotenoids >= 0', name='ck_fruit_nutritions_carotenoids_nonnegative'),
    sa.CheckConstraint('energy >= 0', name='ck_fruit_nutritions_energy_nonnegative'),
    sa.CheckConstraint('fiber >= 0', name='ck_fruit_nutritions_fiber_nonnegative'),
    sa.CheckConstraint('folate >= 0', name='ck_fruit_nutritions_folate_nonnegative'),
    sa.CheckConstraint('potassium >= 0', name='ck_fruit_nutritions_potassium_nonnegative'),
    sa.CheckConstraint('vitamin_c >= 0', name='ck_fruit_nutritions_vitamin_c_nonnegative'),
    sa.ForeignKeyConstraint(['fruit_id'], ['public.fruits.id'], name=op.f('fk_fruit_nutritions_fruit_id_fruits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fruit_nutritions')),
    sa.UniqueConstraint('fruit_id', name='uq_fruit_nutritions_fruit_id'),
    schema='public'
    )
    op.create_table('fruit_seasons',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('fruit_id', sa.BigInteger(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('start_month', sa.SmallInteger(), nullable=False),
    sa.Column('end_month', sa.SmallInteger(), nullable=False),
    sa.Column('season_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_month BETWEEN 1 AND 12', name='ck_fruit_seasons_end_month_range'),
    sa.CheckConstraint('season_score BETWEEN 0 AND 1', name='ck_fruit_seasons_score_range'),
    sa.CheckConstraint('start_month BETWEEN 1 AND 12', name='ck_fruit_seasons_start_month_range'),
    sa.ForeignKeyConstraint(['fruit_id'], ['public.fruits.id'], name=op.f('fk_fruit_seasons_fruit_id_fruits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fruit_seasons')),
    sa.UniqueConstraint('fruit_id', 'region', 'start_month', 'end_month', name='uq_fruit_seasons_fruit_region_months'),
    schema='public'
    )
    op.create_index('ix_fruit_seasons_region_fruit_id', 'fruit_seasons', ['region', 'fruit_id'], unique=False, schema='public')
    op.create_table('recommendations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation_date', sa.Date(), nullable=False),
    sa.Column('refresh_number', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'replaced')", name='ck_recommendations_status_values'),
    sa.CheckConstraint('refresh_number >= 0', name='ck_recommendations_refresh_number_nonnegative'),
    sa.CheckConstraint('total_score BETWEEN 0 AND 1', name='ck_recommendations_total_score_range'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], name=op.f('fk_recommendations_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    sa.UniqueConstraint('user_id', 'recommendation_date', 'refresh_number', name='uq_recommendations_user_date_refresh'),
    schema='public'
    )
    op.create_index('ix_recommendations_user_history', 'recommendations', ['user_id', sa.literal_column('recommendation_date DESC'), sa.literal_column('refresh_number DESC')], unique=False, schema='public')
    op.create_index('uq_recommendations_active_user_date', 'recommendations', ['user_id', 'recommendation_date'], unique=True, schema='public', postgresql_where=sa.text("status = 'active'"))
    op.create_table('user_fruit_preferences',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fruit_id', sa.BigInteger(), nullable=False),
    sa.Column('preference_score', sa.Numeric(precision=4, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('is_forbidden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('preference_score BETWEEN -1 AND 2', name='ck_user_fruit_preferences_score_range'),
    sa.ForeignKeyConstraint(['fruit_id'], ['public.fruits.id'], name=op.f('fk_user_fruit_preferences_fruit_id_fruits'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], name=op.f('fk_user_fruit_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_fruit_preferences')),
    sa.UniqueConstraint('user_id', 'fruit_id', name='uq_user_fruit_preferences_user_fruit'),
    schema='public'
    )
    op.create_index('ix_user_fruit_preferences_fruit_id', 'user_fruit_preferences', ['fruit_id'], unique=False, schema='public')
    op.create_table('recommendation_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('fruit_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(reasons) = 'array'", name='ck_recommendation_items_reasons_array'),
    sa.CheckConstraint('rank IN (1, 2)', name='ck_recommendation_items_rank_values'),
    sa.CheckConstraint('score BETWEEN 0 AND 1', name='ck_recommendation_items_score_range'),
    sa.ForeignKeyConstraint(['fruit_id'], ['public.fruits.id'], name=op.f('fk_recommendation_items_fruit_id_fruits'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['public.recommendations.id'], name=op.f('fk_recommendation_items_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_items')),
    sa.UniqueConstraint('recommendation_id', 'fruit_id', name='uq_recommendation_items_recommendation_fruit'),
    sa.UniqueConstraint('recommendation_id', 'rank', name='uq_recommendation_items_recommendation_rank'),
    schema='public'
    )
    op.create_index('ix_recommendation_items_fruit_id', 'recommendation_items', ['fruit_id'], unique=False, schema='public')
    op.create_table('recommendation_feedback',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('recommendation_item_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("feedback_type IN ('eaten', 'liked', 'disliked', 'unavailable', 'expensive', 'tired_of_it', 'change_requested')", name='ck_recommendation_feedback_type_values'),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['public.recommendation_items.id'], name='fk_rec_feedback_item_id_items', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], name=op.f('fk_recommendation_feedback_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_feedback')),
    sa.UniqueConstraint('recommendation_item_id', 'user_id', 'feedback_type', name='uq_recommendation_feedback_item_user_type'),
    schema='public'
    )
    op.create_index('ix_recommendation_feedback_user_created_at', 'recommendation_feedback', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """只删除本 migration 创建的基础业务对象。"""
    """Revert the migration in a disposable test database only."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendation_feedback_user_created_at', table_name='recommendation_feedback', schema='public')
    op.drop_table('recommendation_feedback', schema='public')
    op.drop_index('ix_recommendation_items_fruit_id', table_name='recommendation_items', schema='public')
    op.drop_table('recommendation_items', schema='public')
    op.drop_index('ix_user_fruit_preferences_fruit_id', table_name='user_fruit_preferences', schema='public')
    op.drop_table('user_fruit_preferences', schema='public')
    op.drop_index('uq_recommendations_active_user_date', table_name='recommendations', schema='public', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_recommendations_user_history', table_name='recommendations', schema='public')
    op.drop_table('recommendations', schema='public')
    op.drop_index('ix_fruit_seasons_region_fruit_id', table_name='fruit_seasons', schema='public')
    op.drop_table('fruit_seasons', schema='public')
    op.drop_table('fruit_nutritions', schema='public')
    op.drop_table('users', schema='public')
    op.drop_table('fruits', schema='public')
    # ### end Alembic commands ###
